name: Generate SHASUMs
on:
  push:
    branches:
      - main
    paths:
      - "templates/scripts/**.sh"
  workflow_dispatch:

jobs:
  generate-shasums:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate shasum.txt
        run: |
          cd templates/scripts
          sha256sum bootstrap.sh > ../../shasum.txt
          sha256sum simple.sh >> ../../shasum.txt

      - name: Commit shasum.txt
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: update shasum.txt"
          file_pattern: shasum.txt
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
